// Generated by dart_native_codegen.
// https://pub.dev/packages/dart_native_codegen

import 'dart:ffi';

import 'package:dart_native/dart_native.dart';
import 'package:dart_native_gen/dart_native_gen.dart';
import '../another_package/Node.dart';
import 'IDNJavaSample.dart';

class DNJavaSample {
  int getArgA() {}
  void setArgA(int argA) {}
  int getArgB() {}
  void setArgB(int argB) {}
  Node getArgC() {}
  void setArgC(Node argC) {}

  IDNJavaSample getWrapper() {}
  void setWrapper(IDNJavaSample wrapper) {}
  int arg(int a, byte b, short c, long d, float e, double f, char g, boolean h,
      String i) {}
  List<Node> insertToList(List<Node> nodeList, Node node) {}
}
